name: Track Contributions

on:
  schedule:
    - cron: '0 0 * * 7'  # Runs every Sunday at midnight UTC

  workflow_dispatch:  # Allows manual execution

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contribution Data
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/Scaler-Innovation-Labs/Excel_Clone_SST_OS/contributors" > contributions.json

      - name: Commit & Push Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add contributions.json
          git commit -m "Updated weekly contributions"
          git push
