name: Track Contributions

on:
  schedule:
    - cron: '0 0 * * 0'  # ✅ Runs every Sunday at midnight UTC

  workflow_dispatch:  # Allows manual execution

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures manual authentication is used

      - name: Fetch Contribution Data
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/Scaler-Innovation-Labs/Excel_Clone_SST_OS/contributors" > contributions.json

      - name: Setup Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Commit & Push Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add contributions.json
          git commit -m "Updated weekly contributions"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Scaler-Innovation-Labs/Excel_Clone_SST_OS.git
